apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-pod
  namespace: app
  labels:
    app: aws-cli

spec:
  containers:
    - name: aws-cli-container
      image: amazon/aws-cli
      command: ["sleep", "infinity"]
  serviceAccountName: app-service-account
