apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: app
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::258845600139:role/iamr-x-eks-cluster-pod-identity-role"
